name: "Рецепты и полезные советы по использованию Git SCM"
markdown: redcarpet
markdown_ext: md
pygments: true
timezone: Europe/Simferopol

include: ['_pages']
relative_permalinks: false
permalink: /:year/:categories/:title.html

url: "http://127.0.0.1:4000"
author: "Сергей Сергеев"

host: 127.0.0.1
port: 4000
